---
# Preliminary tasks that should always be run
# List users in order to look files inside each home directory

- name: "PRELIM | Section 1.1 | Create list of mount points"
  set_fact:
      mount_names: "{{ ansible_mounts | map(attribute='mount') | list }}"



- name: "PRELIM | Section 4.1 | Configure System Accounting (auditd)"
  package:
      name: audit
      state: present
  vars:
      ansible_python_interpreter: /bin/python

- name: "PRELIM | Section 5.1 | Configure cron"
  package:
      name: cronie
      state: present
  vars:
      ansible_python_interpreter: /bin/python

### NOTE: You will need to adjust the UID range in parenthases below.
### ALSO NOTE: We weed out any user with a home dir not in standard locations because interactive users shouldn't have those paths as a home dir. Add or removed directory paths as needed below.
- name: "PRELIM | 6.2.8 | Gather local interactive user directories"
  shell: "getent passwd {1000..65535} | cut -d: -f6 | sort -u | grep -v '/var/' | grep -v '/nonexistent/*' | grep -v '/run/*'"
  changed_when: false
  failed_when: false
  register: amazon2cis_6_2_8_getent
  tags:
      - skip_ansible_lint
      - rule_6.2.8

- name: "PRELIM | 6.2.8 | Set fact for home directory paths for interactive users"
  set_fact:
      amazon2cis_stig_interactive_homedir_results: "{{ amazon2cis_6_2_8_getent.stdout_lines }}"
  when:
      - amazon2cis_6_2_8_getent.stdout_lines is defined
  tags:
      - rule_6.2.8
